### ISSUE TITLE
Adverts Not Showing

### ISSUE THREAD

**Issue by html5andblog** [admob-google/admob-cordova#11]
The adverts just aren't showing up in my phonegap build.

I've added the plugin with: 
cordova plugin add com.admob.plugin

In the config.xml file I've added the line: 
<gap:plugin name="com-admob-plugin" version="5.2.0" source="npm"/>

And then I'm using the JavaScript:

```javascript
document.addEventListener("deviceready",onDeviceReady,false);

        function onDeviceReady() {
                        
            admob.initAdmob("Admob code");
            admob.showBanner(admob.BannerSize.BANNER,admob.Position.BOTTOM_CENTER);
            
        }

```

**Comment by admob-google** [comment]
admob.initAdmob("admob banner ID","admob interstitial ID");

**Comment by html5andblog** [comment]
Thanks for your reply. I was including it like that. I just removed it for the example here. The problem has turned out to be with the onDeviceReady function not running.
