### ISSUE TITLE
Local sounds stop working when admob cordova installed

### ISSUE THREAD

**Issue by gregstein** [admob-google/admob-cordova#13]
Hello,

Local sounds do not work when this plugin or any other admob plugin is installed. However for some reason external sounds (e.g: http://website.com/sound.mp3) work.

is there a way to make the local sounds work? Because when I uninstall this plugin every local sound works a like charm!!

Thank you,

**Comment by admob-google** [comment]
any log or debug infomation?

**Comment by gregstein** [comment]
I use intel xdk and the app generates very normal no bugs!

**Comment by gregstein** [comment]
here is the code i use to play my audio sounds:

	  <audio id="player" controls="controls" style="width:100%">
  <source src="#" type="audio/ogg">
  <source src="#" type="audio/mp3">
</audio>
<br>

<button class="myButton" onclick="track('http://externalwebsite.com/test.mp3')">01 Yes</button><br>
<button class="myButton" onclick="track('02_No.mp3')">02 No</button><br>

<script>
// one, and only one, function for playing
function track(ogg, mp3){
  var player = document.getElementById('player');
  // wrong
  // var sourceOgg=document.getElementById('player');
  // var sourceMp3=document.getElementById('player');
  player.children[0].src = ogg;
  player.children[1].src = mp3;
  player.load();
  player.play(); 
}



</script>

There must be something in the admob plugin that is blocking local mp3 files from playing.

**Comment by gregstein** [comment]
Thank you for your time!! I am currently using external links.
