### ISSUE TITLE
Intel XDK not building, xdk: early access 2866. commit: Master

### ISSUE THREAD

**Issue by arjankuijpers** [admob-google/admob-cordova#18]
i'm currently using a early access version of XDK (2866) and this plugin is not building (with my settings).
gettting an error while building:

file is universal (2 slices) but does not contain a(n) armv7s slice.

/Plugins/com.admob.plugin/AdmobAPI.framework/AdmobAPI file 'Appname/Plugins/com.admob.plugin/AdmobAPI.framework/AdmobAPI' for architecture armv7s
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **

**Comment by gregstein** [comment]
Hello,

Remove the plugin and reinstall it by only inputting the plugin id: 
`com.admob.plugin`

(Do not input version)

Now rebuild your app.

If the build fails create a new project , copy your app files in it and install admob as mentioned above. At this point, It can not fail, but if it does there is a plugin that causing the issue, try to remove them one by one and rebuild.

**Comment by admob-google** [comment]
remove armv7s from your project setting ,it is not reqired.

**Comment by gregstein** [comment]
Go with admob-google solution first  :)

**Comment by arjankuijpers** [comment]
Not seeing a option in Intel XDK to disable armv7s.

**Comment by gregstein** [comment]
In Project tab>Plugin settings

**Comment by arjankuijpers** [comment]
the whole plugin ..? 
<img width="1156" alt="schermafbeelding 2016-02-12 om 00 34 57" src="https://cloud.githubusercontent.com/assets/1952012/12994429/e5567200-d120-11e5-99d4-3bcc9e9d2660.png">

**Comment by gregstein** [comment]
I think it's AppVersion that you need to delete

**Comment by gregstein** [comment]
by the way did you touch Launch Icons and Splash Screens ? You fill in the icons but avoid Splash screen because whenever i try to setup splash screen I get error compiling the app, so I had to create new project and drag my html files into it and compiling works.

**Comment by ugierth** [comment]
I am facing the same error and tried to remove and reinstall as admob-google mentioned, but without luck. I can build the iOS app without errors if the admit-plugin is not part of the app. So I think the armv7s could be at admob plugin. Is there any way to disable it?
Thanks, Uwe

**Comment by gregstein** [comment]
Create a new fresh project and add only admob, and also do not fill the Splash screens.

**Comment by ugierth** [comment]
Do you think that this is a solution? I need the plugin working at my app
Cheers Uwe

**Comment by gregstein** [comment]
I also use intel xdk and it is buggy as hell, and at least that seems to solve for me.

**Comment by arjankuijpers** [comment]
@gregstein which version of XDK do you use and so using Early Access version .. the versioning of EA is different.

**Comment by gregstein** [comment]
@arjankuijpers I always update to the latest one and make sure i use higher version of cordova v.4.1.1 or v.5 or above. Do not use lower versions sooner google play will stop the support for that.

**Comment by arjankuijpers** [comment]
new blank project without plugins succeeding iOS builds, com.admob.plugin added trough git (master) fails log: https://gist.github.com/arjankuijpers/14c810d14992d4968e6b

**Comment by arjankuijpers** [comment]
![image](https://cloud.githubusercontent.com/assets/1952012/13013663/ad3a5784-d1b0-11e5-946e-282c548a8a0e.png)

**Comment by arjankuijpers** [comment]
![screen_failed_blank](https://cloud.githubusercontent.com/assets/1952012/13013722/e7724b1e-d1b0-11e5-89b7-122a55562f0a.png)

**Comment by gregstein** [comment]
Please change to cordova CLI version: http://i.imgur.com/ugY1S0C.png

and try to re-upload and re-build

**Comment by arjankuijpers** [comment]
it is no longer supported to use that version
![image](https://cloud.githubusercontent.com/assets/1952012/13013949/d5f3549a-d1b1-11e5-80a9-5e18a1998b53.png)

**Comment by gregstein** [comment]
Odd! Try this plugin : https://github.com/appfeel/admob-google-cordova instead of this one see if it works

**Comment by gregstein** [comment]
install like this: http://i.imgur.com/oOoWoXh.png

**Comment by arjankuijpers** [comment]
fails aswell ![screen_failed_blank_appfeel](https://cloud.githubusercontent.com/assets/1952012/13014264/3e28e830-d1b3-11e5-9428-97b4710bc0c8.png)

**Comment by arjankuijpers** [comment]
https://gist.github.com/arjankuijpers/c3815c213c9ffb6a6ec5

**Comment by gregstein** [comment]
create another empty project and try to rebuild with that plugin again. 

if it doesn't work, try this plugin too in another project: https://github.com/floatinghotpot/cordova-plugin-admob. Also keep the name of the app as default so u know what's the problem.

**Comment by gregstein** [comment]
If all these plugins fail. 100% the early access version that is causing it.

**Comment by arjankuijpers** [comment]
Had the same thing with the stable version, but I will try the normal before confirming that.

**Comment by arjankuijpers** [comment]
if its not to much to ask: could you create an XDK project with com.admob.plugin ?
and zip this (and attach file). then I can validate if this problem is my setup.

**Comment by gregstein** [comment]
sure

**Comment by gregstein** [comment]
Here is the link to the sample project:http://www.mediafire.com/download/v526rr6hf4cs345/admobsample.zip

and here is a success android build screen with that project: http://prntscr.com/a2euvi

**Comment by arjankuijpers** [comment]
normal fails as well at xdk 2893, havnt tried your zip yet.

![app-blank-with-plugin-fail](https://cloud.githubusercontent.com/assets/1952012/13017324/dbfaa084-d1c3-11e5-848a-61c1264f7ca9.png)
![app-blank-withoutplugin-suc](https://cloud.githubusercontent.com/assets/1952012/13017325/dbfd02fc-d1c3-11e5-8e08-c4bae2b59042.png)
![app-blank-with-plugin-appfeel-fail](https://cloud.githubusercontent.com/assets/1952012/13017326/dbffbe70-d1c3-11e5-9553-84817bf9a155.png)

https://gist.github.com/arjankuijpers/28028e0e2c8e2b04aff7

**Comment by arjankuijpers** [comment]
your Zip also fails, have you tried building iOS ?, because the screenshot you added is from Android and my plugins work on Android aswell but it need to be working both platforms.

**Comment by admob-google** [comment]
add armv7s support?

**Comment by arjankuijpers** [comment]
that would be great, because this is really a plugin I want to use before the others

**Comment by arjankuijpers** [comment]
if its not that hard, I could take a look to help, but I dont know where to begin :)

**Comment by ugierth** [comment]
Hi, if I understand the error message correct there is a compiler/linker flag to create also for armv7s architecture. But with using xcode 6 and iOS 8 apple removed armv7s. Please take a look at
https://github.com/openframeworks/openFrameworks/issues/3423
if you update the flag to armv7 it should build without error. 
Cheers, Uwe

**Comment by arjankuijpers** [comment]
Well, you can solve this when you build with xcode but with Intel XDK you can't change Intel build settings. And Xcode stuff gets done on server side and is not in your control.

**Comment by arjankuijpers** [comment]
I don't know if the plugin creator can do anything to fix this without Intelsat support to change the build archs

**Comment by arjankuijpers** [comment]
I the commit history there is a commit named add support for armv7s [#beaa0c](https://github.com/admob-google/admob-cordova/commit/beaa0c995bf5fceaa69c3a3e0ce55149b431ae03) so isnt it already supported ?

I cant fully understand if the plugin needs to support armv7s or needs to drop this (if it already supports)

**Comment by ugierth** [comment]
From your debug post I can see:
Build settings from command line:
    ARCHS = armv7 armv7s arm64
This will be used for the "ld" command and its failing because of missing armv7s. So my last comment was wrong. The armv7s slice is missing at AdmobAPI file. maybe the maintainer can recompile with added arch flag armv7s

**Comment by arjankuijpers** [comment]
is it maintained by google or is it a creation of this Admob project.. otherwise I could change and compile it myself right ? 
framework name used by this project: AdmobAPI.framework
framework name downloaded from Google Admob download pages: GoogleMobileAds.framework

**Comment by ugierth** [comment]
Sorry I don't know if this is maintaned by google. The file included at this plugin is a compiled binary.

**Comment by arjankuijpers** [comment]
thats why I ask :) but its a question for the maintainer I guess.

**Comment by admob-google** [comment]
wait

**Comment by admob-google** [comment]
upgraded

**Comment by ugierth** [comment]
sorry to say but the build is also failing with upgraded plugin:

ld: file is universal (4 slices) but does not contain a(n) armv7s slice: SuggestMe/Plugins/admob/AdmobAPI.framework/AdmobAPI file 'SuggestMe/Plugins/admob/AdmobAPI.framework/AdmobAPI' for architecture armv7s

if you need the complete build log I can send it.

**Comment by admob-google** [comment]
upgraded ,5.4.1
