### ISSUE TITLE
Build failed with Adobe phonegap build

### ISSUE THREAD

**Issue by loecsen** [admob-google/admob-cordova#2]
Hello,

I tried to build an application with phonegap build and I got the following log as the build failed for iOS only:
(this only an extract of the log file)

Ld build/Loecsen.build/Release-iphoneos/Loecsen.build/Objects-normal/armv7s/Loecsen normal armv7s
    cd /project
    export IPHONEOS_DEPLOYMENT_TARGET=6.0
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch armv7s -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -L/project/build -F/project/build -FLoecsen/Plugins/com.admob.plugin -filelist /project/build/Loecsen.build/Release-iphoneos/Loecsen.build/Objects-normal/armv7s/Loecsen.LinkFileList -dead_strip -weak_framework CoreFoundation -weak_framework UIKit -weak_framework AVFoundation -weak_framework CoreMedia -weak-lSystem -force_load /project/build/libCordova.a -ObjC -fobjc-arc -fobjc-link-runtime -miphoneos-version-min=6.0 -framework AssetsLibrary /project/build/libCordova.a -framework CoreGraphics -framework MobileCoreServices -framework CoreMotion -weak_framework AudioToolbox -weak_framework ImageIO -framework CoreLocation -weak_framework SystemConfiguration -weak_framework AddressBook -weak_framework AddressBookUI -lz -framework AdmobAPI -framework EventKit -framework EventKitUI -framework StoreKit -framework AdSupport -framework MessageUI -framework AVFoundation -framework Foundation -framework UIKit -Xlinker -dependency_info -Xlinker /project/build/Loecsen.build/Release-iphoneos/Loecsen.build/Objects-normal/armv7s/Loecsen_dependency_info.dat -o /project/build/Loecsen.build/Release-iphoneos/Loecsen.build/Objects-normal/armv7s/Loecsen
ld: file is universal (4 slices) but does not contain a(n) armv7s slice: Loecsen/Plugins/com.admob.plugin/AdmobAPI.framework/AdmobAPI file 'Loecsen/Plugins/com.admob.plugin/AdmobAPI.framework/AdmobAPI' for architecture armv7s
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **

The following build commands failed:
	Ld build/Loecsen.build/Release-iphoneos/Loecsen.build/Objects-normal/armv7s/Loecsen normal armv7s
(1 failure)

Is there anything to do ?

Thx

L.

**Comment by admob-google** [comment]
upgrade to new version.fixed.
