### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by arjankuijpers** [admob-google/admob-cordova#20]
It is hard to see what version the current Repo is on, and what the latest version @ npm.js is

commits with versions in Title will help, also making releases or edit the readme with latest version at the top.

ofcours you can see this in the plugin.xml but in commits would be great.

**Comment by arjankuijpers** [comment]
what is the newest stable version ..?

**Comment by admob-google** [comment]
5.3.0 and 5.3.1

**Comment by admob-google** [comment]
upgraded
