### ISSUE TITLE
Not compatible with cordova 6.0.0 or platform iOS@4.0.1

### ISSUE THREAD

**Issue by arjankuijpers** [admob-google/admob-cordova#21]
When using this plugin does not compile with cordova 6 and ios-platform version 4.0.1

https://cordova.apache.org/news/2016/01/28/tools-release.html

other plugins work, its not a project problem.

no visible @interface for 'AdmobAdPlugin' declares the selector
      'writeJavascript:'
    [self writeJavascript:json];

no visible @interface for 'CDVPlugin' declares the selector
      'initWithWebView:'
    self = (AdmobAdPlugin *)[super initWithWebView:theWebView];

no visible @interface for 'NSDictionary' declares the selector
      'integerValueForKey:defaultValue:'
    int adx=(int)[params integerValueForKey:@"x" defaultValue:0];

no visible @interface for 'NSDictionary' declares the selector
      'integerValueForKey:defaultValue:'
    int ady=(int)[params integerValueForKey:@"y" defaultValue:0];

no visible @interface for 'NSDictionary' declares the selector
      'integerValueForKey:defaultValue:'
    int width= (int)[params integerValueForKey:@"bannerWidth" defaultValue:0];

no visible @interface for 'NSDictionary' declares the selector
      'integerValueForKey:defaultValue:'
    int height=(int) [params integerValueForKey:@"bannerHeight" defaultValue:0];

**Comment by admob-google** [comment]
wait

**Comment by admob-google** [comment]
upgraded
