### ISSUE TITLE
banner at bottom cuts footer line

### ISSUE THREAD

**Issue by ugierth** [admob-google/admob-cordova#22]
Hi, I am working on on iOS App and use your latest build which is not failing at the XDK build server anymore (great job, thanks). But now I am facing another issue. My App has header and footer and if I am looking at your example pictures all looks fine. I tried first a smart_banner at bottom_app and bottom_center and the displayed banner is overlaying the footer line so that no button is visible:

![bottom_app](https://cloud.githubusercontent.com/assets/17121957/13253956/3c0d73b0-da3f-11e5-9471-df6eecafeb22.jpg)

next I tried top_app but this time the banner increased the whole view and the buttons at the footer line were moved out:

![top_app](https://cloud.githubusercontent.com/assets/17121957/13254018/a1a7f0c4-da3f-11e5-991b-a01362d080fc.jpg)
 
at the next pic you can see the App without any banner:

![normal_view](https://cloud.githubusercontent.com/assets/17121957/13254030/b547ded2-da3f-11e5-8099-8614bc981d6f.jpg)

Do you have any idea how to add the banner below the footer line? Any help is welcome!
Thanks Uwe

**Comment by admob-google** [comment]
fixed    ,enjoy it.

**Comment by ugierth** [comment]
thanks its working fine :-)
