### ISSUE TITLE
Plugin stop working with XDK 3088

### ISSUE THREAD

**Issue by htsnet** [admob-google/admob-cordova#23]
The plugin stop working after upgrade XDK to version 3088 (now using cordova-plugin-admobpro version 2.13.0). 

I am trying to debug the admob.js. It seems the crash is in this line: if( window.plugins && window.plugins.AdMob )

I inserted 2 lines before, to show the content: 

alert("plugins " + window.plugins);
alert("admob " + window.plugins.AdMob);

The first element is showed as undefined and the second crash the javascript.

I don´t know why... Is there a problem in XDK? Is there a way to fix it?

**Comment by admob-google** [comment]
Maybe not install plugin success

**Comment by htsnet** [comment]
Yes, amost it...
I found the issue: the admob.js was not compatible with the plugin. I erase all and reinstall everything. The new admob.js is completely diferent from the old one.
Thanks.

**Comment by admob-google** [comment]
updated
