### ISSUE TITLE
Inconsistent page covering behavior

### ISSUE THREAD

**Issue by blukis** [admob-google/admob-cordova#24]
Using admob.BannerSize.SMART_BANNER,and position admob.Position.BOTTOM_APP, 
`<plugin name="admob" version="5.4.2"/>`
page covering behavior is inconsistent between Android & iOS:
- On Android, webview above ad is shrunk so bottom of webview touches top of ad.  When I scroll webview to the bottom, I see the entirety of the webview's content.
- On iOS, webview extends to bottom of screen, and bottom of webview is covered up by ad.  When I scroll webview to the bottom, I cannot see the bottom N pixels of my app because content is covered up by ad.

**Comment by admob-google** [comment]
updated
