### ISSUE TITLE
Unable to work together with analytics plugin

### ISSUE THREAD

**Issue by fobus42** [admob-google/admob-cordova#25]
Hi,

Bot this and admob (https://github.com/danwilson/google-analytics-plugin) plugin works good if they are not installed together. But When I'm installing them together I'm getting this error.

` Manifest merger failed : Attribute meta-data#com.google.android.gms.version@value value=(8115000) from AndroidManifest.xml:12:66-89

```
    is also present at [com.google.android.gms:play-services-basement:9.4.0] AndroidManifest.xml:23:13-66 value=(@integer/google_play_services_version).

    Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:12:9-92 to override.
```

`

How can I fix it?

**Comment by fobus42** [comment]
Here is an answer for you : https://github.com/danwilson/google-analytics-plugin/issues/262#issuecomment-237294619

**Comment by fobus42** [comment]
Here is @FairyDwarves fixed the problem : https://github.com/FairyDwarves/admob-cordova

**Comment by admob-google** [comment]
updated

**Comment by fobus42** [comment]
Thank you!
