### ISSUE TITLE
Problem with analytics & admob plugin

### ISSUE THREAD

**Issue by loecsen** [admob-google/admob-cordova#4]
Hello,

I use this plugin "com.admob.plugin" (http://plugins.cordova.io/#/package/com.admob.plugin) and com.analytics.google (https://github.com/appfeel/analytics-google-demo) to display ad into my app, but when I use phonegap build, I get this error (I had the same with local build)

[dependency] Found 2 versions of google-play-services.jar in the dependency list,
[dependency] but not all the versions are identical (check is based on SHA-1 only at this time).
[dependency] All versions of the libraries must be the same at this time.
[dependency] Versions found are:
[dependency] Path: /project/com.google.play.services/google-play-services_lib/libs/google-play-services.jar
[dependency] 	Length: 4221621
[dependency] 	SHA-1: 38c2f8e192dc24ddbf6cae2784f3d4267af66a3e
[dependency] Path: /project/libs/google-play-services.jar
[dependency] 	Length: 2301201
[dependency] 	SHA-1: 1acfaa1f3f8821659ffb68ddcd83801ac04a253b

BUILD FAILED
/home/ec2-user/android-sdk/tools/ant/build.xml:577: Jar mismatch! Fix your dependencies

Any idea to solve this issue ?

Kind regards

L.

**Comment by admob-google** [comment]
upgraded
