### ISSUE TITLE
plug-in crashing android app(interface not implemented error)

### ISSUE THREAD

**Issue by ramu14321** [admob-google/admob-cordova#9]
I tried hard 2 days and finally i am hopeless and in end of road towards this issue,Please help me out to get admob working for me. I followed all instructions and used plug-in my phonegap app but when ever I try to show banner or Interstitial my android app crashing by saying "interface not implemented" error
Here is complete error stack trace.

W/dalvikvm( 1055): threadid=1: thread exiting with uncaught exception (group=0x419b4c08)
E/AndroidRuntime( 1055): FATAL EXCEPTION: main
E/AndroidRuntime( 1055): Process: com.phonegap.helloworld, PID: 1055
E/AndroidRuntime( 1055): java.lang.IncompatibleClassChangeError: interface not implemented
E/AndroidRuntime( 1055):        at com.admob.cordova.plugin.BannerListener.fireEvent(BannerListener.java:16)
E/AndroidRuntime( 1055):        at com.admob.cordova.plugin.BannerListener.onAdLoaded(BannerListener.java:39)
E/AndroidRuntime( 1055):        at com.google.android.gms.ads.internal.client.zzc.onAdLoaded(Unknown Source)
E/AndroidRuntime( 1055):        at com.google.android.gms.ads.internal.client.zzm$zza.onTransact(Unknown Source)
E/AndroidRuntime( 1055):        at android.os.Binder.transact(Binder.java:361)
E/AndroidRuntime( 1055):        at com.google.android.gms.ads.internal.client.l.c(SourceFile:152)
E/AndroidRuntime( 1055):        at com.google.android.gms.ads.internal.a.q(SourceFile:697)
E/AndroidRuntime( 1055):        at com.google.android.gms.ads.internal.a.b(SourceFile:369)
E/AndroidRuntime( 1055):        at com.google.android.gms.ads.internal.b.b(SourceFile:152)
E/AndroidRuntime( 1055):        at com.google.android.gms.ads.internal.o.f.a(SourceFile:130)
E/AndroidRuntime( 1055):        at com.google.android.gms.ads.internal.o.h.run(SourceFile:115)
E/AndroidRuntime( 1055):        at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime( 1055):        at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 1055):        at android.os.Looper.loop(Looper.java:146)
E/AndroidRuntime( 1055):        at android.app.ActivityThread.main(ActivityThread.java:5602)
E/AndroidRuntime( 1055):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 1055):        at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 1055):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
E/AndroidRuntime( 1055):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
E/AndroidRuntime( 1055):        at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager( 2468):   Force finishing activity com.phonegap.helloworld/.Koteeswar

va.lang.IncompatibleClassChangeError: interface not implemented
E/AndroidRuntime(31259):        at com.admob.cordova.plugin.BDInterstitialAdListener.fireEvent(BDInterstitialAdListener.java:19)
E/AndroidRuntime(31259):        at com.admob.cordova.plugin.BDInterstitialAdListener.onAdLoaded(BDInterstitialAdListener.java:42)
E/AndroidRuntime(31259):        at com.google.android.gms.ads.internal.client.zzc.onAdLoaded(Unknown Source)
E/AndroidRuntime(31259):        at com.google.android.gms.ads.internal.client.zzm$zza.onTransact(Unknown Source)
E/AndroidRuntime(31259):        at android.os.Binder.transact(Binder.java:361)
E/AndroidRuntime(31259):        at com.google.android.gms.ads.internal.client.l.c(SourceFile:152)
E/AndroidRuntime(31259):        at com.google.android.gms.ads.internal.a.q(SourceFile:697)
E/AndroidRuntime(31259):        at com.google.android.gms.ads.internal.t.q(SourceFile:277)
E/AndroidRuntime(31259):        at com.google.android.gms.ads.internal.a.b(SourceFile:369)
E/AndroidRuntime(31259):        at com.google.android.gms.ads.internal.b.b(SourceFile:152)
E/AndroidRuntime(31259):        at com.google.android.gms.ads.internal.o.f.a(SourceFile:130)
E/AndroidRuntime(31259):        at com.google.android.gms.ads.internal.o.n.a(SourceFile:102)
E/AndroidRuntime(31259):        at com.google.android.gms.ads.internal.o.h.run(SourceFile:115)
E/AndroidRuntime(31259):        at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime(31259):        at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(31259):        at android.os.Looper.loop(Looper.java:146)
E/AndroidRuntime(31259):        at android.app.ActivityThread.main(ActivityThread.java:5602)
E/AndroidRuntime(31259):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(31259):        at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(31259):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
E/AndroidRuntime(31259):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
E/AndroidRuntime(31259):        at dalvik.system.NativeStart.main(Native Method)
W/ActivityThread(31259): ClassLoader.loadClass: The class loader returned by Thread.getContextClassLoader() may fail for processes that host multiple applications. You should explicitly specify a context class loader. For example: Thread.setContextClassLoader(getClass().getClassLoader());
W/ActivityManager( 2471):   Force finishing activity com.phonegap.helloworld/.Koteeswar

**Comment by ramu14321** [comment]
Here are my cordova and admob versions i used.
>cordova -v
5.2.0
>cordova plugin
admob 5.0.4 "AdmobPlugin"

**Comment by admob-google** [comment]
fix install from git   https://github.com/admob-google/admob-cordova.git
